<%@ Page Title="" Language="C#" MasterPageFile="~/User/Usermaster.master" AutoEventWireup="true" CodeFile="About Us.aspx.cs" Inherits="User_About_Us" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">

        .style1
        {
            width: 100%;
            font-family: Arial, Helvetica, sans-serif;
        }
        .style4
        {
            text-align: center;
            font-size: xx-large;
        }
        .style5
        {
            font-size: small;
        }
        .auto-style9 {
            font-size: medium;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
    <table cellpadding="10" cellspacing="5" class="style1">
    <tr>
        <td class="style4"><asp:Image ID="Image3" runat="server" Height="250px" ImageUrl="~/images/about1.png" Width="100%" />
        </td>
    </tr>
    <tr>
        <td style="text-align: justify"><span class="auto-style9">Online Optic Shop</span><span style="color: rgb(0, 0, 0); font-family: &quot;Neue Montreal&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;" class="auto-style9"> and Clinic is a leader in crafting stylish, high-quality, eyewear at affordable prices. &nbsp;Online Optic Shop 
            operates more than 250+ retail locations across Maharashtra, Sangli,Satara,Kolhapur, Pune, Nashik, Nagpur, Solhapur, Mumbai and also expanding into other cities. Online Optic shop 
            offers a wide variety of fashionable eyewear with high quality with a focus on reinventing the eyewear shopping experience, exceptional service with an unprecedented level of speed and convenience to make the process of buying glasses fun and enjoyable.</span><span style="color: rgb(0, 0, 0); font-family: &quot;Neue Montreal&quot;; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: justify; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><br />
            <br />
            <div id="s-0b48d764-deb1-4f30-b838-9f00573bd122" class="shg-c  " style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 17px; line-height: inherit; font-family: &quot;Neue Montreal&quot;; vertical-align: baseline; overflow-wrap: break-word; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <div class="shogun-heading-component" style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; overflow-wrap: break-word;">
                    <h1 style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 30px; line-height: 1.2; font-family: &quot;Neue Montreal&quot;; vertical-align: baseline; overflow-wrap: break-word; letter-spacing: 0px; color: rgb(0, 0, 0); text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">&nbsp;<strong>Mission</strong></h1>
                </div>
            </div>
            <div id="s-5ad32076-e4e5-4c37-b7d8-3b8ae897ba6d" class="shg-c  " style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 17px; line-height: inherit; font-family: &quot;Neue Montreal&quot;; vertical-align: baseline; overflow-wrap: break-word; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <div class="shg-rich-text shg-theme-text-content" style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; overflow-wrap: break-word;">
                    <p style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.3; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">
                        To provide the best in vision by providing the most advanced , comfortable , latest and affordable eyewear.&nbsp;</p>
                    <h1 style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 30px; line-height: 1.2; font-family: &quot;Neue Montreal&quot;; vertical-align: baseline; overflow-wrap: break-word; letter-spacing: 0px; color: rgb(0, 0, 0); text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;"><strong>Vision</strong></h1>
                    <p style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.3; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">
                        Every individual should be able to access affordable eyecare and make it a part of their daily lives to see the world better.&nbsp;</p>
                </div>
            </div>
            <div id="s-db0688fe-7b41-4573-a4b0-f46675d84404" class="shg-c  " style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 17px; line-height: inherit; font-family: &quot;Neue Montreal&quot;; vertical-align: baseline; overflow-wrap: break-word; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <div class="shogun-heading-component" style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; overflow-wrap: break-word;">
                    <h1 style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 30px; line-height: 1.2; font-family: &quot;Neue Montreal&quot;; vertical-align: baseline; overflow-wrap: break-word; letter-spacing: 0px; color: rgb(0, 0, 0); text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;"><strong>At This Site You Will Get...</strong></h1>
                </div>
            </div>
            <div id="s-49d20ec3-aa5d-4a2e-86eb-664388977b71" class="shg-c  " style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 17px; line-height: inherit; font-family: &quot;Neue Montreal&quot;; vertical-align: baseline; overflow-wrap: break-word; color: rgb(0, 0, 0); letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                <div class="shg-rich-text shg-theme-text-content" style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; overflow-wrap: break-word;">
                    <p style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.3; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">
                        <strong style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word;">Simple and Affordable Pricing</strong></p>
                    <p style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.3; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">
                        We as a brand, believe in providing customers with complete transparency pricing and satisfying every customer with affordability &amp; Wallet-Friendliness.</p>
                    <p style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.3; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">
                        <strong style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word;">14 Day Returns</strong></p>
                    <p style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.3; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">
                        We know sometimes what you buy may not suit you. Its a fair point and we would take the responsibility for it.<span>&nbsp;</span><strong style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word;">Just return in 14 days</strong><span>&nbsp;</span>and get a complete refund with no&nbsp;questions asked.&nbsp;</p>
                    <p style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.3; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">
                        <strong style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word;">Unconditional Warranty on all products</strong></p>
                    <p style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.3; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">
                        There are no complicated conditions for our warranty replacements. All that you would need to do, walk-in near-by Online Optic Shop Store with your bill to get your replacement, it’s as simple as that.</p>
                    <p style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.3; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">
                        <strong style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word;">Latest in Design and Technology</strong></p>
                    <p style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.3; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">
                        Our research team keeps creating new designs and advancements both in lenses and frames. We ensure that we only provide you with the latest in eyewear &nbsp;and you never would be left behind.&nbsp;</p>
                    <p style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.3; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">
                        <strong style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 700; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word;">Exceptional Service</strong></p>
                    <p style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); outline: none !important; margin: 0px 0px 12px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: inherit; line-height: 1.3; font-family: inherit; vertical-align: baseline; overflow-wrap: break-word; text-rendering: optimizelegibility; -webkit-font-smoothing: antialiased;">
                        Be it online or offline our team is here to always assist you and ensure that your purchase experience is always a memorable one and we will ensure to go that extra mile to see you happy.&nbsp;</p>
                </div>
            </div>
            </span></td>
    </tr>
</table>
</asp:Content>

